import MARIO_GAME_ANIMATION_404_ERROR_PAGE_V3 from "/mario404.gif";
export { MARIO_GAME_ANIMATION_404_ERROR_PAGE_V3 };
export const VITE_PORTFOLIO_ACCESS_TOKEN=String(import.meta.env.VITE_PORTFOLIO_ACCESS_TOKEN)